sudo: required
dist: trusty

language: php

services:
  - docker


    
before_script:
    - git submodule add https://github.com/Laradock/laradock.git laradock
    - cd laradock
    - docker-compose up -d apache2 mysql
    - docker-compose exec workspace bash
    - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'
    - php artisan key:generate
    - mysql -u root --password="" travis_ci_test < business-manners-quiz-test.sql
    - sleep 3


script:
    - phpunit
