sudo: required
dist: trusty

services:
  - docker

addons:
    chrome: stable

before_install:
    - sudo apt-get remove docker docker-engine
    - sudo apt-get update
    - sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
    - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get install docker-ce
    
before_script:
    - git submodule add https://github.com/Laradock/laradock.git laradock
    - cd laradock
    - cp env-example .env
    - sudo service mysql stop
    - docker-compose up -d apache2 mysql
    - docker-compose run workspace composer update --lock
    - cd ../
    - mv business-manners-quiz-test.sql laradock
    - cp .env.example .env
    - cp .env .env.dusk.local
    - sudo chmod 755 vendor/laravel/dusk/bin/*
    - cd laradock
    - docker-compose run workspace php artisan key:generate
    - docker exec -i $(docker-compose ps -q mysql) mysql -u default --password=secret default < business-manners-quiz-test.sql

script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - docker-compose run workspace php artisan serve &
    - sleep 3
    - which chromedriver-linux
    - docker-compose run workspace ./vendor/bin/phpunit
    - docker-compose run workspace php artisan dusk
