sudo: required
dist: xenial

language: php

php:
    - 7.0

services:
  - mysql

addons:
  mariadb: '10.0'
  chrome: stable

install:
  - travis_retry composer install --no-interaction
    
before_script:
    - cp .env.travis .env
    - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'
    - php artisan key:generate
    - mysql -u root --password="" travis_ci_test < business-manners-quiz-test.sql
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - php artisan serve &
    - sleep 3


script:
    - phpunit
    - php artisan dusk
