language: php

php:
    - 7.0

services:
  - mysql

addons:
  mariadb: '10.0'

before_install:
    - sudo mysql -u root --password="" -p travis_ci_test < business-manners-quiz-test.sql

before_script:
    - cp .env.travis .env
    - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate


script:
    - phpunit
