sudo: required
dist: trusty

language: php

services:
  - docker

before_install:
    - apt-get remove docker docker-engine
    - apt-get update
    - apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
    - apt-get install apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt-get update
    - apt-get install docker-ce
    
before_script:
    - git submodule add https://github.com/Laradock/laradock.git laradock
    - cd laradock
    - cp env-example .env
    - docker-compose up -d apache2 mysql
    - docker-compose exec workspace bash
    - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'
    - php artisan key:generate
    - mysql -u root --password="" travis_ci_test < business-manners-quiz-test.sql
    - sleep 3


script:
    - phpunit
