sudo: required
dist: trusty

language: php

php:
    - 7.0

services:
  - mysql

addons:
  mariadb: '10.0'
  chrome: stable
    
before_script:
    - cp .env.travis .env
    - travis_retry composer install --no-interaction
    - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - mysql -u root --password="" travis_ci_test < business-manners-quiz-test.sql
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - php artisan serve &


script:
    - phpunit
    - php artisan dusk
