version: "3"
services:
  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - db
    ports:
      - 9000:9000
    volumes:
      - ../:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    container_name: "4qmysql"
  node:
    image: node:8.15.1-alpine #8が使いたいので8を指定
    user: node
    working_dir: /home/node/app
    volumes:
      - ../:/home/node/app #package.jsonがあるディレクトリをmountすること